// tools.js — shared tool data for tools.html and tool.html
// Schema: { id, group, mark, icon, name, sub, pricing, url, x, github, deepLink, purpose }
//   icon    : Simple Icons slug  (https://simpleicons.org) — leave '' if unknown
//   x       : X / Twitter profile URL (optional)
//   github  : GitHub profile or repo URL (optional)
//   deepLink: 'supported' | 'planned' | 'none'

var TOOL_GROUPS = {
  'chat':      'Chat UIs',
  'coding':    'Coding',
  'infra':     'Infra',
  'local':     'Local / Self-host',
  'knowledge': 'Knowledge',
  'agents':    'Agents'
};

var TOOLS = [

  // ---- Chat UIs ----
  { id: 'claude',          group: 'chat',      mark: 'CL', icon: 'anthropic',        name: 'Claude',            sub: 'Anthropic',           pricing: 'freemium', url: 'https://claude.ai/',                                        x: 'https://x.com/AnthropicAI',     github: 'https://github.com/anthropics',                     deepLink: 'planned',   purpose: 'The reference chat UI for long-context and hard-reasoning work. Strong defaults for structured outputs and agentic tasks.' },
  { id: 'chatgpt',         group: 'chat',      mark: 'GP', icon: 'openai',           name: 'ChatGPT',           sub: 'OpenAI',              pricing: 'freemium', url: 'https://chatgpt.com/',                                      x: 'https://x.com/OpenAI',          github: 'https://github.com/openai',                          deepLink: 'supported', purpose: 'Most popular chat UI. Widest ecosystem of GPTs, plugins, and integrations. Strong at code and multi-modal tasks.' },
  { id: 'gemini',          group: 'chat',      mark: 'GE', icon: 'googlegemini',     name: 'Gemini',            sub: 'Google',              pricing: 'freemium', url: 'https://gemini.google.com/',                                x: 'https://x.com/GoogleDeepMind',  github: 'https://github.com/google-deepmind',                 deepLink: 'planned',   purpose: "Google's chat UI with tight Workspace and Search integration. Strong multimodal and long-context." },
  { id: 'grok',            group: 'chat',      mark: 'GR', icon: 'x',                name: 'Grok',              sub: 'xAI',                 pricing: 'freemium', url: 'https://grok.com/',                                         x: 'https://x.com/xai',             github: 'https://github.com/xai-org',                         deepLink: 'none',      purpose: "xAI's chat UI. Integrated with X, leans unfiltered, useful for crypto and market-adjacent research." },
  { id: 'perplexity',      group: 'chat',      mark: 'PX', icon: 'perplexity',       name: 'Perplexity',        sub: 'Perplexity',          pricing: 'freemium', url: 'https://www.perplexity.ai/',                                x: 'https://x.com/perplexity_ai',   github: 'https://github.com/perplexity-ai',                   deepLink: 'supported', purpose: 'Answer engine with inline citations. Best when research + sourcing matters more than raw generation.' },
  { id: 'lechat',          group: 'chat',      mark: 'LC', icon: 'mistralai',        name: 'Le Chat',           sub: 'Mistral',             pricing: 'free',     url: 'https://chat.mistral.ai/',                                  x: 'https://x.com/MistralAI',       github: 'https://github.com/mistralai',                       deepLink: 'none',      purpose: "Mistral's chat UI. European-hosted, fast and capable. Good GDPR-friendly alternative to US-hosted options." },
  { id: 'deepseek',        group: 'chat',      mark: 'DS', icon: 'deepseek',         name: 'DeepSeek',          sub: 'DeepSeek',            pricing: 'free',     url: 'https://chat.deepseek.com/',                                x: 'https://x.com/deepseek_ai',     github: 'https://github.com/deepseek-ai',                     deepLink: 'none',      purpose: 'Competitive reasoning at very low cost. Consider data-residency implications before sending sensitive content.' },
  { id: 'copilot-ms',      group: 'chat',      mark: 'MC', icon: 'microsoftcopilot', name: 'Microsoft Copilot', sub: 'Microsoft',           pricing: 'freemium', url: 'https://copilot.microsoft.com/',                            x: 'https://x.com/Microsoft',       github: 'https://github.com/microsoft',                       deepLink: 'none',      purpose: "Microsoft's consumer AI powered by GPT-4o. Tight Windows and Office 365 integration for enterprise users." },
  { id: 'cohere',          group: 'chat',      mark: 'CO', icon: 'cohere',           name: 'Coral',             sub: 'Cohere',              pricing: 'freemium', url: 'https://coral.cohere.com/',                                 x: 'https://x.com/cohere',          github: 'https://github.com/cohere-ai',                       deepLink: 'none',      purpose: 'Enterprise-focused chat with strong retrieval augmentation. Good for grounding answers in large document sets.' },

  // ---- Coding ----
  { id: 'claude-code',     group: 'coding',    mark: 'CC', icon: 'anthropic',        name: 'Claude Code',       sub: 'Anthropic CLI',       pricing: 'paid',     url: 'https://claude.ai/code',                                    x: 'https://x.com/AnthropicAI',     github: 'https://github.com/anthropics/claude-code',          deepLink: 'none',      purpose: 'Agentic CLI. Reads and edits your repo, runs commands, ships PRs. Best pairing for long-form engineering prompts.' },
  { id: 'codex',           group: 'coding',    mark: 'CX', icon: 'openai',           name: 'Codex',             sub: 'OpenAI',              pricing: 'paid',     url: 'https://chatgpt.com/codex',                                 x: 'https://x.com/OpenAI',          github: 'https://github.com/openai',                          deepLink: 'planned',   purpose: "OpenAI's cloud-hosted coding agent inside ChatGPT. Strong at multi-file tasks and repo-level reasoning." },
  { id: 'cursor',          group: 'coding',    mark: 'CR', icon: 'cursor',           name: 'Cursor',            sub: 'Anysphere',           pricing: 'freemium', url: 'https://cursor.com/',                                       x: 'https://x.com/cursor_ai',       github: 'https://github.com/getcursor',                       deepLink: 'none',      purpose: 'VS Code fork with deep AI integration. Strong at inline edits and multi-file refactors. Most popular among full-time devs.' },
  { id: 'windsurf',        group: 'coding',    mark: 'WS', icon: 'codeium',          name: 'Windsurf',          sub: 'Codeium',             pricing: 'freemium', url: 'https://windsurf.com/',                                     x: 'https://x.com/codeium',         github: 'https://github.com/Exafunction/codeium',             deepLink: 'none',      purpose: 'IDE with agentic Cascade flows. Cursor competitor with stronger multi-step execution and background agents.' },
  { id: 'cline',           group: 'coding',    mark: 'CN', icon: 'visualstudiocode', name: 'Cline',             sub: 'VS Code extension',  pricing: 'byok',     url: 'https://cline.bot/',                                        x: 'https://x.com/clinedotbot',     github: 'https://github.com/cline/cline',                     deepLink: 'none',      purpose: 'Open-source agentic coding extension for VS Code. Bring your own API key; no vendor lock-in.' },
  { id: 'aider',           group: 'coding',    mark: 'AD', icon: 'gnubash',          name: 'Aider',             sub: 'open source CLI',    pricing: 'byok',     url: 'https://aider.chat/',                                       x: 'https://x.com/aider_ai',        github: 'https://github.com/paul-gauthier/aider',             deepLink: 'none',      purpose: 'Terminal-based coding agent. Minimal, scriptable, and git-native. The power-user choice for AI-assisted development.' },
  { id: 'copilot',         group: 'coding',    mark: 'CP', icon: 'githubcopilot',    name: 'GitHub Copilot',    sub: 'GitHub',              pricing: 'paid',     url: 'https://github.com/features/copilot',                       x: 'https://x.com/GitHubCopilot',   github: 'https://github.com/features/copilot',                deepLink: 'none',      purpose: 'The mainstream IDE autocomplete + chat. Ubiquitous in JetBrains and VS Code; works where the others don\'t.' },
  { id: 'zed',             group: 'coding',    mark: 'ZA', icon: 'zedindustries',    name: 'Zed AI',            sub: 'Zed',                 pricing: 'freemium', url: 'https://zed.dev/',                                          x: 'https://x.com/zeddotdev',       github: 'https://github.com/zed-industries/zed',              deepLink: 'none',      purpose: 'High-performance native editor with built-in AI. Fast, opinionated, and Rust-based. Requires a mindset shift from VS Code.' },
  { id: 'bolt',            group: 'coding',    mark: 'BL', icon: 'stackblitz',       name: 'Bolt.new',          sub: 'StackBlitz',          pricing: 'freemium', url: 'https://bolt.new/',                                         x: 'https://x.com/stackblitz',      github: 'https://github.com/stackblitz',                      deepLink: 'none',      purpose: 'Browser-based full-stack app builder. Prompt to running app in seconds. No local setup; great for fast prototyping.' },
  { id: 'v0',              group: 'coding',    mark: 'V0', icon: 'vercel',           name: 'v0',                sub: 'Vercel',              pricing: 'freemium', url: 'https://v0.dev/',                                           x: 'https://x.com/vercel',          github: 'https://github.com/vercel',                          deepLink: 'none',      purpose: 'UI generation from prompts. Outputs React and shadcn/ui code you can paste straight into your project.' },
  { id: 'replit',          group: 'coding',    mark: 'RI', icon: 'replit',           name: 'Replit',            sub: 'Replit',              pricing: 'freemium', url: 'https://replit.com/',                                       x: 'https://x.com/Replit',          github: 'https://github.com/replit',                          deepLink: 'none',      purpose: 'Browser IDE with AI agent. Good for prototyping and shipping small apps without any local setup overhead.' },

  // ---- Infra ----
  { id: 'openrouter',      group: 'infra',     mark: 'OR', icon: 'openrouter',       name: 'OpenRouter',        sub: 'model router',        pricing: 'paid',     url: 'https://openrouter.ai/',                                    x: 'https://x.com/OpenRouterAI',    github: 'https://github.com/openrouterapp',                   deepLink: 'none',      purpose: 'Unified API across dozens of frontier and open models. Route by cost, latency, or capability — one key, all providers.' },
  { id: 'groq',            group: 'infra',     mark: 'GQ', icon: 'groq',             name: 'Groq',              sub: 'inference',           pricing: 'freemium', url: 'https://groq.com/',                                         x: 'https://x.com/GroqInc',         github: 'https://github.com/groq',                            deepLink: 'none',      purpose: 'Extremely fast inference on select open models via custom LPU hardware. Best for low-latency experimentation.' },
  { id: 'hf',              group: 'infra',     mark: 'HF', icon: 'huggingface',      name: 'Hugging Face',      sub: 'model hub',           pricing: 'freemium', url: 'https://huggingface.co/',                                   x: 'https://x.com/huggingface',     github: 'https://github.com/huggingface',                     deepLink: 'none',      purpose: 'The model hub. Browse, run, and fine-tune thousands of open-weight models. Inference API covers most everyday use cases.' },
  { id: 'replicate',       group: 'infra',     mark: 'RE', icon: 'replicate',        name: 'Replicate',         sub: 'inference',           pricing: 'paid',     url: 'https://replicate.com/',                                    x: 'https://x.com/replicate',       github: 'https://github.com/replicate',                       deepLink: 'none',      purpose: 'Hosted inference for open-source models. Strongest for multimodal (image, audio, video) experiments via API.' },
  { id: 'aistudio',        group: 'infra',     mark: 'AI', icon: 'googlegemini',     name: 'AI Studio',         sub: 'Google',              pricing: 'free',     url: 'https://aistudio.google.com/',                              x: 'https://x.com/GoogleAI',        github: 'https://github.com/google/generative-ai-python',     deepLink: 'none',      purpose: "Google's Gemini playground. Generous free tier, long context, and easy API key creation." },
  { id: 'anthropic-console', group: 'infra',   mark: 'AC', icon: 'anthropic',        name: 'Anthropic Console', sub: 'Anthropic',           pricing: 'paid',     url: 'https://console.anthropic.com/',                            x: 'https://x.com/AnthropicAI',     github: 'https://github.com/anthropics',                      deepLink: 'none',      purpose: "Claude's developer console. Prompt evaluation, workbench, API key management, and usage analytics." },
  { id: 'together',        group: 'infra',     mark: 'TA', icon: 'togetherai',       name: 'Together AI',       sub: 'inference',           pricing: 'paid',     url: 'https://www.together.ai/',                                  x: 'https://x.com/togethercompute', github: 'https://github.com/togethercomputer',                 deepLink: 'none',      purpose: 'Fast, affordable inference for open-source models. Good for production workloads where Groq capacity is limited.' },
  { id: 'fireworks',       group: 'infra',     mark: 'FW', icon: '',                 name: 'Fireworks AI',      sub: 'inference',           pricing: 'paid',     url: 'https://fireworks.ai/',                                     x: 'https://x.com/FireworksAI',     github: 'https://github.com/fw-ai',                           deepLink: 'none',      purpose: 'Optimised inference for open-source models with function-calling support. Targets compound AI and agentic workloads.' },

  // ---- Local / Self-host ----
  { id: 'ollama',          group: 'local',     mark: 'OL', icon: 'ollama',           name: 'Ollama',            sub: 'local runner',        pricing: 'free',     url: 'https://ollama.com/',                                       x: 'https://x.com/ollama',          github: 'https://github.com/ollama/ollama',                   deepLink: 'none',      purpose: 'Run open-weight models locally via CLI and HTTP API. The standard entry point for self-hosted LLMs on Mac and Linux.' },
  { id: 'lmstudio',        group: 'local',     mark: 'LM', icon: '',                 name: 'LM Studio',         sub: 'desktop app',         pricing: 'free',     url: 'https://lmstudio.ai/',                                      x: 'https://x.com/LMStudio_AI',     github: '',                                                   deepLink: 'none',      purpose: 'Desktop GUI for downloading and running local models. The most approachable on-ramp for non-terminal users.' },
  { id: 'jan',             group: 'local',     mark: 'JN', icon: '',                 name: 'Jan',               sub: 'open source desktop', pricing: 'free',     url: 'https://jan.ai/',                                           x: 'https://x.com/janframework',    github: 'https://github.com/janhq/jan',                       deepLink: 'none',      purpose: 'Open-source, offline-first chat UI. Model-agnostic, extensible via extensions, no cloud dependency.' },
  { id: 'localai',         group: 'local',     mark: 'LA', icon: '',                 name: 'LocalAI',           sub: 'OpenAI-compatible',   pricing: 'free',     url: 'https://localai.io/',                                       x: 'https://x.com/LocalAI_API',     github: 'https://github.com/mudler/LocalAI',                  deepLink: 'none',      purpose: 'Drop-in OpenAI-compatible API server for local models. Swap cloud calls for local without changing your SDK code.' },
  { id: 'gpt4all',         group: 'local',     mark: 'G4', icon: '',                 name: 'GPT4All',           sub: 'Nomic',               pricing: 'free',     url: 'https://www.nomic.ai/gpt4all',                              x: 'https://x.com/nomic_ai',        github: 'https://github.com/nomic-ai/gpt4all',                deepLink: 'none',      purpose: 'Privacy-first local chat with pre-packaged quantized models. Runs on modest hardware, no internet needed.' },
  { id: 'openwebui',       group: 'local',     mark: 'OW', icon: '',                 name: 'Open WebUI',        sub: 'open source',         pricing: 'free',     url: 'https://openwebui.com/',                                    x: 'https://x.com/OpenWebUI',       github: 'https://github.com/open-webui/open-webui',           deepLink: 'none',      purpose: 'Self-hosted web UI for Ollama and OpenAI-compatible backends. Feature-rich, actively maintained, Docker-friendly.' },

  // ---- Knowledge / PKM ----
  { id: 'obsidian',        group: 'knowledge', mark: 'OB', icon: 'obsidian',         name: 'Obsidian',          sub: 'local markdown vault', pricing: 'freemium', url: 'https://obsidian.md/',                                     x: 'https://x.com/obsdmd',          github: 'https://github.com/obsidianmd',                      deepLink: 'none',      purpose: 'Local-first markdown notebook. Pairs with MCP, Smart Connections, and the Copilot plugin to become an AI-readable second brain.' },
  { id: 'logseq',          group: 'knowledge', mark: 'LS', icon: 'logseq',           name: 'Logseq',            sub: 'outliner, local-first', pricing: 'free',   url: 'https://logseq.com/',                                       x: 'https://x.com/logseq',          github: 'https://github.com/logseq/logseq',                   deepLink: 'none',      purpose: 'Open-source outliner with bidirectional links. Plain text on disk; straightforward for agents and scripts to parse.' },
  { id: 'notion',          group: 'knowledge', mark: 'NT', icon: 'notion',           name: 'Notion',            sub: 'collaborative docs',   pricing: 'freemium', url: 'https://www.notion.so/',                                   x: 'https://x.com/NotionHQ',        github: 'https://github.com/makenotion',                      deepLink: 'none',      purpose: 'Cloud doc workspace with an official MCP server. Best when your knowledge lives in a shared team wiki.' },
  { id: 'mem',             group: 'knowledge', mark: 'ME', icon: '',                 name: 'Mem',               sub: 'AI notes',             pricing: 'freemium', url: 'https://mem.ai/',                                          x: 'https://x.com/memdotai',        github: '',                                                   deepLink: 'none',      purpose: 'AI-native note-taking that auto-organises itself. Semantic search over your notes without manual tagging.' },

  // ---- Agents ----
  { id: 'langchain',       group: 'agents',    mark: 'LC', icon: 'langchain',        name: 'LangChain',         sub: 'framework',           pricing: 'free',     url: 'https://langchain.com/',                                    x: 'https://x.com/LangChainAI',     github: 'https://github.com/langchain-ai/langchain',          deepLink: 'none',      purpose: 'The dominant framework for LLM applications and agents. Large ecosystem of integrations, chains, and memory abstractions.' },
  { id: 'langgraph',       group: 'agents',    mark: 'LG', icon: 'langchain',        name: 'LangGraph',         sub: 'orchestration',       pricing: 'free',     url: 'https://langchain-ai.github.io/langgraph/',                 x: 'https://x.com/LangChainAI',     github: 'https://github.com/langchain-ai/langgraph',          deepLink: 'none',      purpose: 'Graph-based agent orchestration from LangChain. Cleanly handles multi-step, branching, and cyclical agent flows.' },
  { id: 'crewai',          group: 'agents',    mark: 'CW', icon: '',                 name: 'CrewAI',            sub: 'multi-agent',         pricing: 'free',     url: 'https://crewai.com/',                                       x: 'https://x.com/crewAIInc',       github: 'https://github.com/crewAIInc/crewAI',                deepLink: 'none',      purpose: 'Role-based multi-agent framework. Agents get roles, goals, and backstories; tasks are delegated within the crew automatically.' },
  { id: 'autogpt',         group: 'agents',    mark: 'AG', icon: '',                 name: 'AutoGPT',           sub: 'autonomous agent',    pricing: 'free',     url: 'https://agpt.co/',                                          x: 'https://x.com/Auto_GPT',        github: 'https://github.com/Significant-Gravitas/AutoGPT',    deepLink: 'none',      purpose: 'One of the original autonomous agent projects. Reference implementation of long-horizon planning; web and CLI versions.' },
  { id: 'agentops',        group: 'agents',    mark: 'AO', icon: '',                 name: 'AgentOps',          sub: 'observability',       pricing: 'freemium', url: 'https://agentops.ai/',                                      x: 'https://x.com/AgentOpsAI',      github: 'https://github.com/AgentOps-AI/agentops',            deepLink: 'none',      purpose: 'Monitoring and observability for AI agents. Traces token usage, cost, latency, and step-by-step execution across runs.' },
  { id: 'composio',        group: 'agents',    mark: 'CM', icon: '',                 name: 'Composio',          sub: 'tool integrations',   pricing: 'freemium', url: 'https://composio.dev/',                                     x: 'https://x.com/composiohq',      github: 'https://github.com/ComposioHQ/composio',             deepLink: 'none',      purpose: 'Managed integrations layer for AI agents. 100+ tools (GitHub, Gmail, Slack) with auth, rate-limiting, and error handling built in.' }

];
